package com.ticketis.app.model.enums;

public enum WebSocketEventType {
    CREATED,
    UPDATED,
    UPDATED_MANY,
    DELETED,

    IMPORT_TASK_INITIALIZED,

    SYNC_IMPORT_PENDING,
    SYNC_IMPORT_IN_PROGRESS,
    SYNC_IMPORT_FINISHED,
    SYNC_IMPORT_FAILED,

    ASYNC_IMPORT_PROGRESS_STARTED,
    ASYNC_IMPORT_PROGRESS_CHANGED,

    ASYNC_IMPORT_BATCH_IN_PROGRESS,
    ASYNC_IMPORT_BATCH_PROCESSED,
    ASYNC_IMPORT_BATCH_FAILED
    
}
