package com.ticketis.app.model.enums;

public enum WebSocketEventType {
    CREATED,
    UPDATED,
    UPDATED_MANY,
    DELETED,

    IMPORT_TASK_INITIALIZED,

    SYNC_IMPORT_PROGRESS_STARTED,
    SYNC_IMPORT_PROGRESS_PROCESSING,
    SYNC_IMPORT_PROGRESS_SUCCESS,
    SYNC_IMPORT_PROGRESS_FAILED,

    ASYNC_IMPORT_PROGRESS_STARTED,
    ASYNC_IMPORT_PROGRESS_PROCESSING,
    ASYNC_IMPORT_PROGRESS_PARTIAL_SUCCESS,
    ASYNC_IMPORT_PROGRESS_SUCCESS,
    ASYNC_IMPORT_PROGRESS_FAILED,
    ASYNC_IMPORT_PROGRESS_CHANGED,

    ASYNC_IMPORT_BATCH_IN_PROGRESS,
    ASYNC_IMPORT_BATCH_PROCESSED,
    ASYNC_IMPORT_BATCH_FAILED

}
